version: '3.7'

services:
  db:
    image: postgres
    container_name: rentalx-db
    ports:
     - 5432:5432
    environment:
      - POSTGRES_USER=rentalx
      - POSTGRES_PASSWORD=Vaoiwa8321nd
      - POSTGRES_DB=rentalx
    volumes:
      - ./docker-compose/pgdata:/var/lib/postgresql/data
    networks:
      - rentalxNetwork
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: rentalx-app
    ports:
      - 3333:3333
    volumes:
      - ./:/usr/app
    networks:
      - rentalxNetwork
networks:
  rentalxNetwork:
    driver: bridge